name : create-issue

on:
  workflow_dispatch

jobs:
  create-issue
    run-on: ubuntu-latest
    steps:
     - name: Get Token
       id: get_workflow_token
       uses: peter-murray/workflow-application-token-action@v3
       with:
          application_id: ${{ vars.APPLICATION_ID }}
          application_private_key: ${{ secrets.APP_PRIVATE_KEY }}
    
      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v5
        with:
          token: ${{ steps.get_workflow_token.outputs.token }}
          title: An example issue
          content-filepath: .github/ISSUE_TEMPLATE/gsoc_idea.md
          labels: |
            report
            automated issue
            gsoc


  

