name: Sync Contributors and Roadmap
on:
  workflow_dispatch:
jobs:
    sync-contributors-data:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repository  
              uses: actions/checkout@v4
        
            - name: Get Token
              uses: actions/create-github-app-token@v1
              id: get_workflow_token
              with:
                app-id: ${{ vars.APPLICATION_ID }}
                private-key: ${{ secrets.APP_PRIVATE_KEY }}

            - name: Fetch Contributors data
              uses: actions/github-script@v7
              env:
                GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
              with:
                github-token: ${{ env.GH_TOKEN }}
                script: |
                  const fs = require('fs');
                  
                  let data = await github.paginate(github.rest.repos.listContributors, {
                    owner: "json-schema-org",
                    repo: "website",
                    per_page: 100,
                    headers: {
                      "X-GitHub-Api-Version": "2022-11-28",
                    },
                  });
                  
                  console.log(JSON.stringify(data, null, 2));
                  
                  // Filter the data to get only the required fields
                  data = data.map(({ login, id, avatar_url, html_url, contributions }) => 
                    ({ login, id, avatar_url, html_url, contributions }));
                  
                  // Store the data in a file
                  fs.writeFileSync('community.json', JSON.stringify(data, null, 2));
                 
            - name: Commit changes
              env:
                GH_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
              run: |
                git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                git config --global user.name "github-actions[bot]"
                git add community.json
                git commit --amend -m "Update community.json"
                git push https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}.git -f
